export const Producto = [ {
    id: 1,
    nombre: "Laptop",
    precio: 80000,
    stock: 15,
    img: '/public/assets/fotolaptop.jpg',
},
{
    id: 2,
    nombre: "Mouse",
    precio: 5000,
    stock: 16,
    img: "/public/assets/mousefoto.jpg",
},
{
    id: 3,
    nombre: "Teclado",
    precio: 10000,
    stock: 15,
    img: "/public/assets/tecladofoto.jpg",
},
{
    id: 4,
    nombre: "Monitor",
    precio: 22000,
    stock: 12,
    img: "/public/assets/fotomonitor.jpg",
},
{
    id: 5,
    nombre: "Impresora",
    precio: 32000,
    stock: 5,
    img: "/public/assets/fotoimpresora.jpg",
},
{
    id: 6,
    nombre: "Iphone 13 128gb",
    precio:217000 ,
    stock: 10,
    img: "/public/assets/iphone.jpg",
},
{
    id: 7,
    nombre: "Tablet",
    precio:50000 ,
    stock: 10,
    img: "/public/assets/tablet.jpg",
},
{
    id: 8,
    nombre: "Memoria RAM",
    precio:20000 ,
    stock: 15,
    img: "/public/assets/ram.jpg",
},
{
    id: 9,
    nombre: "Memoria HDD",
    precio:15000 ,
    stock: 20,
    img: "/public/assets/hdd.jpg",
},
];

